version: '3.1'

services:
    web :
        build: ./app
        command: node index.js
        volumes:
            - ./app:/usr/app
            - /usr/app/node_modules
        ports:
            - "3001:3000"
        depends_on: 
            - db
        environment:
            DATABASE_URL: postgres://dost:changeme@db:5432/trellodb
    db:
        image: postgres:10
        volumes:
            - ./setup_ex2.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: dost
            POSTGRES_PASSWORD: changeme
            POSTGRES_DB: trellodb

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080